### ISSUE TITLE
Exception in thread “main” java.lang.StackOverflowError

### ISSUE THREAD

**Issue by JishnuPrathap** [databricks/reference-apps#46]
https://github.com/databricks/reference-apps/blob/master/twitter_classifier/scala/src/main/scala/com/databricks/apps/twitter_classifier/ExamineAndTrain.scala

Exception in main java.lang.stackoverflowerror
scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
       at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
       at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
       at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
       at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
       at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)

while executing the following code  
sqlContext.sql("SELECT text FROM tweetTable LIMIT 10").collect().foreach(println)

**Comment by mkanchwala** [comment]
any updates on this?

**Comment by lxn130730** [comment]
how was this issue resolved?

**Comment by mkanchwala** [comment]
I used transformations and actions instead of Where/SQL clauses, It worked for me.

**Comment by lxn130730** [comment]
how to do that? example please
